printWidth: 120
tabWidth: 4
useTabs: false
singleQuote: true
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
quoteProps: as-needed
proseWrap: preserve
endOfLine: crlf
semi: false